apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebpage
  namespace: default  # Ensure namespace is correct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebpage
  template:
    metadata:
      labels:
        app: mywebpage
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: mywebpage
        image: synaxus/mywebpage:latest  # Your container image
        ports:
        - containerPort: 80  # This should match the port in Nginx
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf  # Mount the ConfigMap file
          subPath: default.conf  # Ensure only the file is mounted
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config  # Reference the ConfigMap


