apiVersion: v1
kind: Service
metadata:
  name: mywebpage
  labels:
    app: mywebpage
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: mywebpage
  type: LoadBalancer